name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable
      - run: corepack prepare yarn@4.10.3 --activate
      - run: yarn -v
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            .yarn/cache
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --immutable
      - run: yarn test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/   # важно!
          always-auth: true
      - run: corepack enable
      - run: corepack prepare yarn@4.10.3 --activate
      - run: yarn -v
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            .yarn/cache
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --immutable

      - name: Authenticate to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          npm whoami || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Publish
        run: yarn npm publish --access public --tolerate-republish
